create table public.products (
  sku text primary key,
  name text,
  size text,
  pcs_per_carton integer,
  sale_price numeric
);

create table public.shipments (
  id integer generated by default as identity primary key,
  code text not null unique,
  ship_date date,
  fx_rmb_tnd numeric,
  arrived boolean default false,
  notes text
);

create table public.customers (
  id integer generated by default as identity primary key,
  name text not null,
  phone text,
  notes text,
  created_at timestamptz default now()
);

create table public.sales (
  id integer generated by default as identity primary key,
  sale_date date not null,
  customer_id integer not null references public.customers(id),
  total_tnd numeric not null check (total_tnd >= 0),
  note text,
  created_at timestamptz default now(),
  voided_at timestamptz
);

create table public.sale_items (
  id integer generated by default as identity primary key,
  sale_id integer not null references public.sales(id),
  sku text not null references public.products(sku),
  qty integer not null check (qty > 0),
  unit_price_tnd numeric
);

create table public.payments (
  id integer generated by default as identity primary key,
  pay_date date not null,
  customer_id integer not null references public.customers(id),
  sale_id integer references public.sales(id),
  amount_tnd numeric not null check (amount_tnd > 0),
  method text,
  note text,
  created_at timestamptz default now(),
  voided_at timestamptz
);

create table public.shipment_items (
  id integer generated by default as identity primary key,
  shipment_id integer not null references public.shipments(id),
  sku text not null references public.products(sku),
  cartons integer not null,
  pcs_per_carton integer not null,
  total_pcs integer generated always as (cartons * pcs_per_carton) stored,
  unit_price_rmb numeric not null,
  cbm_total numeric,
  gw_total numeric
);

create table public.shipment_costs (
  id integer generated by default as identity primary key,
  shipment_id integer not null references public.shipments(id),
  cost_date date not null default current_date,
  type text not null,
  label text,
  amount numeric not null,
  currency text not null check (currency in ('RMB', 'USD', 'TND')),
  fx_to_tnd numeric not null default 1,
  basis text not null default 'value' check (basis in ('value', 'cbm', 'pcs')),
  voided_at timestamptz,
  created_at timestamptz default now()
);

create table public.stock_movements (
  id integer generated by default as identity primary key,
  mv_date date not null,
  sku text not null references public.products(sku),
  qty integer not null,
  type text not null check (type in ('arrivage', 'vente', 'casse', 'ajustement')),
  note text,
  shipment_id integer references public.shipments(id),
  created_at timestamptz default now(),
  sale_id integer references public.sales(id)
);

create table public.import_drafts (
  id integer generated by default as identity primary key,
  chat_id bigint not null,
  doc_type text,
  extracted jsonb,
  missing text[],
  status text default 'pending',
  created_at timestamptz default now()
);

create table public.pending_actions (
  id integer generated by default as identity primary key,
  chat_id bigint not null,
  kind text not null,
  payload jsonb not null,
  preview jsonb,
  warning text,
  status text not null default 'pending' check (status in ('pending', 'done', 'failed', 'cancelled', 'expired')),
  result jsonb,
  created_at timestamptz not null default now(),
  done_at timestamptz,
  source_message_id bigint
);

alter table public.products enable row level security;
alter table public.shipments enable row level security;
alter table public.customers enable row level security;
alter table public.sales enable row level security;
alter table public.sale_items enable row level security;
alter table public.payments enable row level security;
alter table public.shipment_items enable row level security;
alter table public.shipment_costs enable row level security;
alter table public.stock_movements enable row level security;
alter table public.import_drafts enable row level security;
alter table public.pending_actions enable row level security;